# Generated by Django 5.0.4 on 2024-08-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb_app', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_pictures/'),
        ),
    ]
