# Generated by Django 5.0.4 on 2024-08-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb_app', '0006_userprofile_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liked_products',
            field=models.ManyToManyField(to='qb_app.product'),
        ),
    ]
