# Generated by Django 4.2.10 on 2024-09-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb_app', '0013_userprofile_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
